"""setup checks on profiles

Revision ID: 9b1c957139b3
Revises: 85db71cd0cc1
Create Date: 2026-10-08 10:08:28.189511
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9b1c957139b3"
down_revision: str | None = "85db71cd0cc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("calendar_ok_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("profiles", sa.Column("login_ok_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "login_ok_at")
    op.drop_column("profiles", "calendar_ok_at")
    # ### end Alembic commands ###
